spring:
  datasource:
    url: jdbc:mysql://localhost:3377/moovsmart?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: on
  mail:
    host: smtp.gmail.com
    port: 587
    username: application.demo7@gmail.com
    password: aietiquhcxlfdusj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  openweathermap:
    api:
      key: 3c00e57613b45fba6cbe0a0c859ab7f3
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
paypal:
  mode: sandbox
  client:
    id: AQ_ZQybzRCfkWn2NdBMwfeYpJynHws9bkDv4BjhHqrcVygI-klHCPrOigQRg5LfSs5eNYZ9yJG2z4Vht
    secret: AQ_ZQybzRCfkWn2NdBMwfeYpJynHws9bkDv4BjhHqrcVygI-klHCPrOigQRg5LfSs5eNYZ9yJG2z4Vht



#  spring.mail.scheduler.persistence.enabled: false
#  spring.mail.scheduler.persistence.redis.embedded: false
#  spring.mail.scheduler.persistence.redis.enabled: false