spring:
  datasource:
    url: jdbc:mysql://localhost:3377/moovsmart?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: on
  mail:
    host: smtp.gmail.com
    port: 587
    username: application.demo7@gmail.com
    password: lrnvustumoozhmpr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  openweathermap:
    api:
      key: 3c00e57613b45fba6cbe0a0c859ab7f3
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  exchangerates:
    api:
      key: e4840fe407a170ac955cb39e55c54ae7
paypal:
  mode: sandbox
  client:
    id: AQ_ZQybzRCfkWn2NdBMwfeYpJynHws9bkDv4BjhHqrcVygI-klHCPrOigQRg5LfSs5eNYZ9yJG2z4Vht
    secret: EN07Ibkeb8_uvPR6jHi-tLgdNQg19oEsICZm8Dsw0KLGl6NsjMpbFhIeYwyqXoq2EpuXlirTDHTqu6GG



